import {setLanguage,getLanguage,setLabel,setText,translate,intlLocale} from './i18n.js';
import {ui,newId,formatMinutes} from './ui.js';import {dateKey,addDays,daysBetween} from './dates.js';import {createPlan,copyPlan,updatePlan,snapshotTask,planSeries,resolvePlanTasks,taskUrgency,planFingerprint} from './plans.js';import {resolveEstimate} from './estimates.js';import {validatePlan} from './plan-validation.js';import {renderLineChart} from './chart-view.js';import {renderScheduleEditor} from './settings-view.js';import {renderPlanEditor} from './plan-editor-view.js';import {renderPlanComparison} from './plan-compare-view.js';
export function createPlannerController(options){
 const {document,planClient,onOpenItem,onComplete,onDirtyChange}=options;const {el,button,input,field,select}=ui(document);const root=el('section','planner-workbench');let data={items:options.items,state:options.state,loadedRange:options.loadedRange,completed:options.completed||{}};let archives={...data.state.plans};let draft=Object.values(archives).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))[0];draft=draft?structuredClone(draft):null;
 let dirty=false,notice='',conflict=false,editing=null,prompt=null,saving=false,destroyed=false;let filters={query:'',course:'all',sort:'dueAsc',group:false,status:'all'};let generating=false,preview=null,previewFingerprint=null,generation=0,progress='';
 const compared=new Set();const openedDays=new Set();let chartMetric='minutes';
 const now=()=>new Date(typeof options.now==='function'?options.now():options.now);const today=()=>dateKey(now(),options.timeZone);
 const facts=()=>({items:data.items,completed:data.completed,now:now().toISOString(),loadedRange:data.loadedRange,state:data.state});
 const mark=value=>{dirty=value;onDirtyChange?.(value);};
 const change=operation=>{try{draft=updatePlan(draft,operation);if(operation.type==='configure')includeCurrentTasks();mark(true);notice='';draw();}catch(error){notice=error.message;draw();}};
 const finishPrompt=value=>{const resolve=prompt?.resolve;prompt=null;draw();resolve?.(value);};
 async function save(){
  if(!draft||saving)return false;const sent=structuredClone(draft);saving=true;draw();let result;
  try{result=await planClient.save(sent,sent.revision);}catch(error){result={ok:false,message:error.message};}
  if(destroyed)return false;saving=false;let clean=false;
  if(result?.ok){archives[result.plan.id]=result.plan;data.state.plans[result.plan.id]=result.plan;
   if(draft?.id===sent.id){clean=JSON.stringify(draft)===JSON.stringify(sent);draft=clean?structuredClone(result.plan):{...draft,revision:result.plan.revision,updatedAt:result.plan.updatedAt};mark(!clean);conflict=false;}
   notice=clean?'Plan saved.':'Earlier changes saved. Your newer edits still need saving.';
  }else{notice=result?.message||'Could not save your plan.';conflict=result?.code==='CONFLICT';}draw();return Boolean(result?.ok&&clean);
 }
 function includeCurrentTasks(){
  if(!draft)return;for(const item of data.items){const eligible=item.type==='assignment'?item.endDay<=draft.range.endDate:item.startDay<=draft.range.endDate&&item.endDay>=draft.range.startDate;
   if(eligible&&!item.completed&&!data.completed[item.key]&&!draft.tasks[item.key]){draft=updatePlan(draft,{type:'addTask',task:snapshotTask(item,{...data.state,completed:data.completed})});mark(true);}
  }
 }

 function discard(){draft=draft&&archives[draft.id]?structuredClone(archives[draft.id]):null;mark(false);editing=null;}
 function requestLeave(){if(generating)cancelGeneration();if(!dirty)return Promise.resolve(true);if(prompt?.kind==='leave')return prompt.promise;let resolve;const promise=new Promise(r=>{resolve=r;});prompt={kind:'leave',resolve,promise};draw();return promise;}
 async function newPlan(){if(!await requestLeave())return;const day=today();draft=createPlan({id:newId('plan'),name:translate(document,'New plan'),items:data.items,state:{...data.state,completed:data.completed},startDate:day,endDate:addDays(day,data.state.settings.schedule.horizonDays-1),timeZone:options.timeZone,now:now()});mark(true);notice='';editing=null;draw();}
 function arrange(itemKey,day=today(),segmentId){const item=data.items.find(i=>i.key===itemKey);if(!draft||(!item&&!draft.tasks[itemKey]))return;if(!draft.tasks[itemKey])draft=updatePlan(draft,{type:'addTask',task:snapshotTask(item,{...data.state,completed:data.completed})});editing={itemKey,day:day<draft.range.startDate?draft.range.startDate:day,segmentId};draw();}
 const formatClock=instant=>new Intl.DateTimeFormat(intlLocale(document,'en-GB'),{timeZone:options.timeZone,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(instant));
 function cancelGeneration(){generation++;options.schedulerClient?.cancel();generating=false;progress='';draw();}
 async function generate(){
  if(!draft||generating)return;
  if(options.ensureRange){try{const fresh=await options.ensureRange(draft.range);if(fresh)data={...data,...fresh};}catch(error){notice=error.message;draw();return;}}
  if(destroyed||!draft)return;includeCurrentTasks();
  const changes=resolvePlanTasks(draft,facts()).changes;if(changes.length){notice='Task data changed. Update plan task data before generating.';draw();return;}
  const version=++generation;const fingerprint=planFingerprint(draft,facts());const input={plan:structuredClone(draft),items:structuredClone(data.items),completed:{...data.completed},now:now().toISOString(),loadedRange:data.loadedRange};
  generating=true;preview=null;progress='Checking deadlines and working windows…';draw();let result;
  try{result=await options.schedulerClient.run(input,{onProgress:p=>{if(generation===version){progress=p.phase==='balancing'?`Balancing · peak ${formatMinutes(p.peakMinutes)}`:`Arranging ${p.day||''}`;const status=root.querySelector('.generation-progress');if(status)setText(status,progress);}}});}catch(error){result={status:'error',message:error.message};}
  if(destroyed||generation!==version)return;generating=false;progress='';
  if(planFingerprint(draft,facts())!==fingerprint){notice='Task estimates, completion or this plan changed during generation. Generate again.';preview=null;draw();return;}
  if(result.status==='error'||result.status==='cancelled'){notice=result.message||'Generation cancelled; your draft is unchanged.';draw();return;}
  preview=result;previewFingerprint=fingerprint;draw();
 }
 function renderPreview(){const panel=el('section','generated-preview');panel.append(el('h3','',preview.status==='complete'?'Generated plan preview':'Partial plan preview'),el('p','hint',`Peak ${formatMinutes(preview.metrics?.beforePeakMinutes||0)} → ${formatMinutes(preview.metrics?.afterPeakMinutes||0)}. Accepting changes the draft; Save keeps the archive.`));if(preview.status==='timeout')panel.append(el('p','notice','Calculation reached its time limit. You can retry; this is not a fully verified success.'));for(const issue of preview.issues||[]){const line=el('p','hint');line.append(el('span','',`${draft.tasks[issue.itemKey]?.title||''}: `,true),el('span','',issue.message));if(issue.missingMinutes)line.append(el('span','',` (${issue.missingMinutes} min missing)`));panel.append(line);}
  panel.append(renderLineChart({document,series:[{id:'generated',name:'Generated remaining work',localizeName:true,color:'#258c83',points:planSeries({...draft,segments:preview.segments}, {...facts(),mode:'remaining'})}],metric:'minutes'}));
  if(preview.validation?.issues.every(i=>i.code==='OVERDUE'))panel.append(button('Accept generated plan',()=>{if(planFingerprint(draft,facts())!==previewFingerprint){preview=null;notice='This plan changed. Generate again.';draw();return;}const checked=validatePlan({...draft,segments:preview.segments},facts());if(checked.issues.some(i=>i.code!=='OVERDUE')){notice='The preview no longer fits current time or task data. Generate again.';preview=null;draw();return;}draft={...draft,segments:structuredClone(preview.segments)};mark(true);preview=null;notice='Generated work accepted into the draft. Save to keep it.';draw();}));panel.append(button('Discard generated preview',()=>{preview=null;draw();},'text-button','Discard preview'));return panel;}
 function draw(){
  if(destroyed)return;setLanguage(document,data.state.settings.language);root.lang=getLanguage(document);const disclosureKey=n=>n.dataset.planDay||n.className||'checks';const disclosures=new Map([...root.querySelectorAll('details')].map(n=>[disclosureKey(n),n.open]));const focused=document.activeElement?.shadowRoot?.activeElement||document.activeElement;const focusId=focused?.dataset?.controlId;const cursor=focused?.selectionStart;const editorKey=editing?JSON.stringify([editing.itemKey,editing.day,editing.segmentId]):null;const currentEditor=root.querySelector('.arrange-editor');const editorValues=currentEditor?.dataset.editorKey===editorKey?Object.fromEntries([...currentEditor.querySelectorAll('input')].map(n=>[n.dataset.controlId,n.value])):null;root.replaceChildren();
  const toolbar=el('div','plan-toolbar');toolbar.append(button('New plan',newPlan));if(Object.keys(archives).length){toolbar.append(select('Saved plans',[['','Choose saved plan'],...Object.values(archives).map(p=>[p.id,p.name,true])],draft?.id||'',async id=>{if(!id)return;if(await requestLeave()){draft=structuredClone(archives[id]);editing=null;notice='';draw();}}));}root.append(toolbar);
  if(draft){toolbar.append(button('Save plan',save,'control',saving?'Saving…':'Save'),button('Copy plan',()=>{draft=copyPlan(draft,{id:newId('plan'),name:`${draft.name.slice(0,110)}${getLanguage(document)==='zh-CN'?' 副本':' copy'}`,now:now()});mark(true);editing=null;draw();}),button('Delete plan',()=>{prompt={kind:'delete'};draw();},'text-button','Delete'));toolbar.querySelector('[data-control-id="Save plan"]').disabled=saving;
   if(options.schedulerClient){toolbar.append(button('Generate balanced plan',generate,'control',generating?'Generating…':'Generate balanced plan'));toolbar.querySelector('[data-control-id="Generate balanced plan"]').disabled=generating;if(generating)toolbar.append(button('Cancel generation',cancelGeneration,'text-button'));}
   const name=input('Plan name',draft.name,'text',value=>change({type:'rename',name:value}));name.maxLength=120;const saveStatus=el('p',dirty?'notice':'hint',dirty?'Unsaved changes':'Saved plan');name.addEventListener('input',()=>{draft=updatePlan(draft,{type:'rename',name:name.value});mark(true);saveStatus.className='notice';setText(saveStatus,'Unsaved changes');});root.append(field('Plan name',name),saveStatus);
   const configuration=el('details','plan-configuration');configuration.append(el('summary','','Plan dates, rest days & capacity'));const range={...draft.range};const schedule=structuredClone(draft.schedule);const applyConfig=()=>change({type:'configure',range,schedule});configuration.append(field('Start date',input('Plan start',range.startDate,'date',v=>{range.startDate=v;applyConfig();})),field('End date',input('Plan end',range.endDate,'date',v=>{range.endDate=v;applyConfig();})),renderScheduleEditor({document,schedule,onChange:applyConfig}));root.append(configuration);
   const resolved=resolvePlanTasks(draft,facts());if(resolved.changes.length)root.append(el('p','notice',`${resolved.changes.length} tasks changed since this plan was saved.`),button('Update plan task data',()=>{const tasks={...draft.tasks};for(const item of data.items)if(tasks[item.key])tasks[item.key]=snapshotTask(item,{...data.state,completed:data.completed});change({type:'updateTasks',tasks});}));
   const validation=validatePlan(draft,facts());const status=el('div','plan-status');status.append(el('strong',validation.complete?'success':'',validation.complete?'All tasks arranged · deadline checks passed':validation.valid?'Draft · some work is not arranged':'Draft · constraints need attention'));
   const remaining=Object.values(validation.unassigned).reduce((n,v)=>n+v,0);if(remaining)status.append(el('span','hint',`${formatMinutes(remaining)} unassigned`));if(validation.issues.length){const details=el('details');details.append(el('summary','',`${validation.issues.length} checks to review`));for(const issue of validation.issues){const line=el('p','hint');line.append(el('span','',`${draft.tasks[issue.itemKey]?.title||issue.day||''} `,true),el('span','',issue.message));details.append(line);}status.append(details);}root.append(status);
   const chartTools=el('div','view-tools');chartTools.append(select('Plan chart metric',[['minutes','Estimated hours'],['tasks','Tasks']],chartMetric,v=>{chartMetric=v;draw();}));root.append(chartTools,renderLineChart({document,series:[{id:draft.id,name:'Planned remaining work',localizeName:true,color:'#258c83',points:planSeries(draft,{...facts(),mode:'remaining'})}],metric:chartMetric,onSelectDay:day=>{openedDays.add(day);draw();root.querySelector(`[data-plan-day="${day}"]`)?.scrollIntoView?.({block:'nearest'});}}));
   if(progress)root.append(el('p','hint generation-progress',progress));if(preview)root.append(renderPreview());
   if(editing)root.append(renderPlanEditor({document,plan:draft,...editing,editorValues,facts:facts(),onApply:change,onClose:()=>{editing=null;draw();}}));
   const columns=el('div','plan-columns');columns.append(pool(),daily());root.append(columns);
  }else root.append(el('div','empty-state','Create a plan to organize your remaining tasks by day.'));
  if(notice)root.append(el('p',conflict?'notice':'hint',notice));if(conflict)root.append(button('Reload saved plan',async()=>{if(options.onReloadPlans){const fresh=await options.onReloadPlans();archives={...fresh.plans};data.state=fresh;}discard();conflict=false;draw();}),button('Save plan as copy',async()=>{draft=copyPlan(draft,{id:newId('plan'),name:`${draft.name.slice(0,110)}${getLanguage(document)==='zh-CN'?' 副本':' copy'}`,now:now()});mark(true);await save();}));
  if(Object.keys(archives).length>=2){const comparison=el('details','comparison-picker');comparison.append(el('summary','','Compare saved plans (2–4)'));for(const saved of Object.values(archives)){const box=input(`Compare ${saved.name}`,'','checkbox');box.checked=compared.has(saved.id);box.addEventListener('change',()=>{if(box.checked&&compared.size<4)compared.add(saved.id);else compared.delete(saved.id);draw();});comparison.append(field(saved.name,box,true));}if(compared.size>=2)comparison.append(renderPlanComparison({document,plans:[...compared].map(id=>archives[id]).filter(Boolean),facts:facts()}));root.append(comparison);}
  if(prompt){const dialog=el('section','draft-dialog');dialog.setAttribute('role','alertdialog');setLabel(dialog,prompt.kind==='leave'?'Unsaved plan':'Delete plan');
   if(prompt.kind==='leave'){dialog.append(el('h3','','Save your plan before leaving?'),button('Save draft and continue',async()=>{if(await save())finishPrompt(true);}),button('Discard draft changes',()=>{discard();finishPrompt(true);},'text-button'),button('Return to editing',()=>finishPrompt(false),'text-button'));}
   else{dialog.append(el('h3','',`Delete “${draft?.name}”?`),el('p','hint','This removes only this saved plan.'),button('Confirm delete plan',async()=>{if(archives[draft.id]){const result=await planClient.remove(draft.id,draft.revision);if(!result.ok){notice=result.message;prompt=null;draw();return;}delete archives[draft.id];delete data.state.plans[draft.id];compared.delete(draft.id);}draft=Object.values(archives)[0]?structuredClone(Object.values(archives)[0]):null;mark(false);prompt=null;draw();}),button('Cancel delete plan',()=>{prompt=null;draw();},'text-button'));}root.append(dialog);
  }
  for(const detail of root.querySelectorAll('details')){const label=disclosureKey(detail);if(disclosures.has(label))detail.open=disclosures.get(label);}
  if(focusId){const target=[...root.querySelectorAll('[data-control-id]')].find(n=>n.dataset.controlId===focusId);target?.focus();if(cursor!=null&&target?.type==='text')target.setSelectionRange(cursor,cursor);}
 }
 function pool(){const panel=el('aside','task-pool');panel.append(el('h3','','Remaining tasks'));const search=input('Search tasks',filters.query);search.addEventListener('input',()=>{filters.query=search.value;draw();});const contexts=new Map();for(const item of data.items)(item.contextCodes||[]).forEach((code,index)=>contexts.set(code,item.contexts[index]||code));
  panel.append(search,select('Task course',[['all','All courses / calendars'],...[...contexts].map(([id,name])=>[id,name,true])],filters.course,v=>{filters.course=v;draw();}),select('Task sort',[['dueAsc','Deadline: nearest first'],['dueDesc','Deadline: latest first'],['estimateAsc','Estimate: shortest first'],['estimateDesc','Estimate: longest first']],filters.sort,v=>{filters.sort=v;draw();}),select('Task arrangement',[['all','All remaining tasks'],['none','Unscheduled'],['partial','Partially scheduled'],['full','Scheduled']],filters.status,v=>{filters.status=v;draw();}));const group=input('Group tasks by course','','checkbox');group.checked=filters.group;group.addEventListener('change',()=>{filters.group=group.checked;draw();});panel.append(field('Group by course',group));
  const amount=key=>draft.segments.filter(s=>s.itemKey===key).reduce((n,s)=>n+(Date.parse(s.endAt)-Date.parse(s.startAt))/60000,0);const estimate=item=>draft.tasks[item.key]?.estimateMinutes||resolveEstimate(item,data.state).minutes;
  const filtered=data.items.filter(i=>!i.completed&&!data.completed[i.key]&&i.title.toLocaleLowerCase().includes(filters.query.trim().toLocaleLowerCase())&&(filters.course==='all'||i.contextCodes?.includes(filters.course))).filter(i=>filters.status==='all'||(filters.status==='none'?amount(i.key)===0:filters.status==='partial'?amount(i.key)>0&&amount(i.key)<estimate(i):amount(i.key)>=estimate(i)));
  filtered.sort((a,b)=>{const n=filters.sort.startsWith('due')?Date.parse(a.dueAt||a.fixedStartAt)-Date.parse(b.dueAt||b.fixedStartAt):estimate(a)-estimate(b);return n*(filters.sort.endsWith('Desc')?-1:1)||a.title.localeCompare(b.title);});
  if(filters.group)filtered.sort((a,b)=>(a.contexts[0]||'Personal').localeCompare(b.contexts[0]||'Personal'));let heading=null;
  for(const item of filtered){if(filters.group&&heading!==(item.contexts[0]||'Personal')){heading=item.contexts[0]||'Personal';panel.append(el('h4','',item.contexts[0]?heading:translate(document,heading),true));}const row=el('div','pool-card');row.dataset.poolTask=item.key;const last=draft.segments.filter(s=>s.itemKey===item.key).map(s=>s.endAt).sort().at(-1);const urgent=taskUrgency(item,{now:now(),lastEndAt:last,completed:false});row.classList.add(`urgency-${urgent.level}`);row.append(button(`Open ${item.title}`,()=>onOpenItem?.(item.key),'task-title',item.title),el('p','hint',item.contexts.join(' · '),true),el('p','hint',`${formatMinutes(estimate(item))} · ${item.type==='event'?'Fixed activity':`${amount(item.key)}/${estimate(item)} min arranged`}`));if(urgent.label)row.append(el('span',`urgency-tag ${urgent.level}`,urgent.label));
   if(item.type==='assignment'){row.draggable=true;row.addEventListener('dragstart',e=>e.dataTransfer?.setData('application/x-canvas-planner-task',item.key));row.append(button(`Arrange ${item.title}`,()=>arrange(item.key),'text-button','Arrange'));}if(!item.canvasCompleted)row.append(button(`Complete ${item.title}`,()=>onComplete?.(item.key,true),'text-button','✓ Complete'));panel.append(row);
  }if(!filtered.length)panel.append(el('p','hint','No remaining tasks match your filters.'));const future=data.items.filter(i=>i.type==='assignment'&&!i.completed&&i.endDay>draft.range.endDate).length;if(future)panel.append(el('p','hint',`${future} future tasks fall after this plan range; use Arrange to include one.`));return panel;
 }
 function daily(){const panel=el('section','daily-plan');panel.append(el('h3','','Your days'));const points=new Map(planSeries(draft,{...facts(),mode:'remaining'}).map(p=>[p.day,p]));const resolved=resolvePlanTasks(draft,facts());
  daysBetween(draft.range.startDate,draft.range.endDate).forEach((day,index)=>{const group=el('details','plan-day');group.dataset.planDay=day;group.open=index<7||openedDays.has(day);group.addEventListener('toggle',()=>{if(group.open)openedDays.add(day);else openedDays.delete(day);});const point=points.get(day);const name=day===today()?'Today':day===addDays(today(),1)?'Tomorrow':new Intl.DateTimeFormat(intlLocale(document),{weekday:'short',month:'short',day:'numeric',timeZone:'UTC'}).format(new Date(`${day}T12:00:00Z`));group.append(el('summary','',`${name} · ${day} · ${point.tasks} tasks · ${formatMinutes(point.minutes)}`));group.addEventListener('dragover',e=>e.preventDefault());group.addEventListener('drop',e=>{e.preventDefault();const key=e.dataTransfer?.getData('application/x-canvas-planner-task');if(data.items.some(i=>i.key===key))arrange(key,day);});
   const blocks=draft.segments.filter(s=>dateKey(s.startAt,draft.timeZone)===day).sort((a,b)=>a.order-b.order||a.startAt.localeCompare(b.startAt));for(const segment of blocks){const task=resolved.tasks[segment.itemKey];if(!task)continue;const row=el('div',`planned-row${task.completed?' completed':''}`);row.append(button(`Open ${task.title}`,()=>onOpenItem?.(task.key),'task-title',task.title),el('span','hint',`${formatClock(segment.startAt)}–${formatClock(segment.endAt)} · ${formatMinutes((Date.parse(segment.endAt)-Date.parse(segment.startAt))/60000)} / ${formatMinutes(task.estimateMinutes)}`));const last=draft.segments.filter(s=>s.itemKey===task.key).map(s=>s.endAt).sort().at(-1);const urgent=taskUrgency(data.items.find(i=>i.key===task.key)||task,{now:now(),lastEndAt:last,completed:task.completed});if(urgent.label)row.append(el('span',`urgency-tag ${urgent.level}`,urgent.label));if(!task.known)row.append(el('span','notice','Not currently loaded'));
    row.append(button(`Edit block ${segment.id}`,()=>arrange(task.key,day,segment.id),'text-button','Edit'),button(`Remove block ${segment.id}`,()=>change({type:'removeSegment',id:segment.id}),'text-button','Remove'),button(`Lock block ${segment.id}`,()=>change({type:'lock',id:segment.id,locked:!segment.locked}),'text-button',segment.locked?'Unlock':'Lock'),button(`Move block ${segment.id} up`,()=>{const ids=blocks.map(s=>s.id);const i=ids.indexOf(segment.id);if(i>0){[ids[i-1],ids[i]]=[ids[i],ids[i-1]];change({type:'reorder',orderedIds:ids});}},'text-button','↑'));
    if(!task.completed&&!data.items.find(i=>i.key===task.key)?.canvasCompleted)row.append(button(`Complete ${task.title}`,()=>onComplete?.(task.key,true),'text-button','✓ Complete'));group.append(row);
   }for(const event of Object.values(draft.tasks).filter(t=>t.type==='event'&&t.startDay<=day&&t.endDay>=day)){const line=el('p',resolved.tasks[event.key]?.completed?'hint completed':'hint');line.append(el('span','',event.title,true),el('span','',' · '),el('span','','Fixed activity'));group.append(line);};if(!blocks.length)group.append(el('p','hint','Drop a task here or use Arrange in the task list.'));panel.append(group);
  });return panel;
 }
 const api={hasPendingLeaveDecision(){return prompt?.kind==='leave';},render(){draw();return root;},setData(next){data={...data,...next};const incoming={...data.state.plans};if(draft&&draft.revision>0&&(!incoming[draft.id]||incoming[draft.id].revision>draft.revision)){if(dirty){conflict=true;notice='This saved plan changed in another page. Reload it or save a copy.';}else draft=incoming[draft.id]?structuredClone(incoming[draft.id]):null;}archives=incoming;draw();},requestLeave,destroy(){generation++;options.schedulerClient?.destroy();destroyed=true;prompt?.resolve?.(false);prompt=null;root.remove();}};return api;
}
