import {ui,newId,formatMinutes} from './ui.js';import {dateKey,addDays,daysBetween} from './dates.js';import {createPlan,copyPlan,updatePlan,snapshotTask,planSeries,resolvePlanTasks,taskUrgency} from './plans.js';import {resolveEstimate} from './estimates.js';import {validatePlan} from './plan-validation.js';import {renderLineChart} from './chart-view.js';import {renderScheduleEditor} from './settings-view.js';import {renderPlanEditor} from './plan-editor-view.js';import {renderPlanComparison} from './plan-compare-view.js';
export function createPlannerController(options){
 const {document,planClient,onOpenItem,onComplete,onDirtyChange}=options;const {el,button,input,field,select}=ui(document);const root=el('section','planner-workbench');let data={items:options.items,state:options.state,loadedRange:options.loadedRange,completed:options.completed||{}};let archives={...data.state.plans};let draft=Object.values(archives).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))[0];draft=draft?structuredClone(draft):null;
 let dirty=false,notice='',conflict=false,editing=null,prompt=null,saving=false,destroyed=false;let filters={query:'',course:'all',sort:'dueAsc',group:false,status:'all'};const compared=new Set();const openedDays=new Set();let chartMetric='minutes';
 const now=()=>new Date(typeof options.now==='function'?options.now():options.now);const today=()=>dateKey(now(),options.timeZone);
 const facts=()=>({items:data.items,completed:data.completed,now:now().toISOString(),loadedRange:data.loadedRange,state:data.state});
 const mark=value=>{dirty=value;onDirtyChange?.(value);};
 const change=operation=>{try{draft=updatePlan(draft,operation);mark(true);notice='';draw();}catch(error){notice=error.message;draw();}};
 const finishPrompt=value=>{const resolve=prompt?.resolve;prompt=null;draw();resolve?.(value);};
 async function save(){if(!draft||saving)return false;saving=true;draw();let result;try{result=await planClient.save(draft,draft.revision);}catch(error){result={ok:false,message:error.message};}if(destroyed)return false;saving=false;if(result?.ok){draft=structuredClone(result.plan);archives[draft.id]=result.plan;data.state.plans[draft.id]=result.plan;mark(false);notice='Plan saved.';conflict=false;}else{notice=result?.message||'Could not save your plan.';conflict=result?.code==='CONFLICT';}draw();return Boolean(result?.ok);}
 function discard(){draft=draft&&archives[draft.id]?structuredClone(archives[draft.id]):null;mark(false);editing=null;}
 function requestLeave(){if(!dirty)return Promise.resolve(true);if(prompt?.kind==='leave')return prompt.promise;let resolve;const promise=new Promise(r=>{resolve=r;});prompt={kind:'leave',resolve,promise};draw();return promise;}
 async function newPlan(){if(!await requestLeave())return;const day=today();draft=createPlan({id:newId('plan'),name:'New plan',items:data.items,state:{...data.state,completed:data.completed},startDate:day,endDate:addDays(day,data.state.settings.schedule.horizonDays-1),timeZone:options.timeZone,now:now()});mark(true);notice='';editing=null;draw();}
 function arrange(itemKey,day=today(),segmentId){const item=data.items.find(i=>i.key===itemKey);if(!draft||(!item&&!draft.tasks[itemKey]))return;if(!draft.tasks[itemKey])draft=updatePlan(draft,{type:'addTask',task:snapshotTask(item,{...data.state,completed:data.completed})});editing={itemKey,day:day<draft.range.startDate?draft.range.startDate:day,segmentId};draw();}
 const formatClock=instant=>new Intl.DateTimeFormat('en-GB',{timeZone:options.timeZone,hour:'2-digit',minute:'2-digit'}).format(new Date(instant));
 function draw(){
  if(destroyed)return;const focused=document.activeElement?.shadowRoot?.activeElement||document.activeElement;const focusId=focused?.dataset?.controlId;const cursor=focused?.selectionStart;root.replaceChildren();
  const toolbar=el('div','plan-toolbar');toolbar.append(button('New plan',newPlan));if(Object.keys(archives).length){toolbar.append(select('Saved plans',[['','Choose saved plan'],...Object.values(archives).map(p=>[p.id,p.name])],draft?.id||'',async id=>{if(!id)return;if(await requestLeave()){draft=structuredClone(archives[id]);editing=null;notice='';draw();}}));}root.append(toolbar);
  if(draft){toolbar.append(button('Save plan',save,'control',saving?'Saving…':'Save'),button('Copy plan',()=>{draft=copyPlan(draft,{id:newId('plan'),name:`${draft.name.slice(0,110)} copy`,now:now()});mark(true);editing=null;draw();}),button('Delete plan',()=>{prompt={kind:'delete'};draw();},'text-button','Delete'));toolbar.querySelector('[aria-label="Save plan"]').disabled=saving;
   const name=input('Plan name',draft.name,'text',value=>change({type:'rename',name:value}));name.maxLength=120;root.append(field('Plan name',name),el('p',dirty?'notice':'hint',dirty?'Unsaved changes':'Saved plan'));
   const configuration=el('details','plan-configuration');configuration.append(el('summary','','Plan dates, rest days & capacity'));const range={...draft.range};const schedule=structuredClone(draft.schedule);const applyConfig=()=>change({type:'configure',range,schedule});configuration.append(field('Start date',input('Plan start',range.startDate,'date',v=>{range.startDate=v;applyConfig();})),field('End date',input('Plan end',range.endDate,'date',v=>{range.endDate=v;applyConfig();})),renderScheduleEditor({document,schedule,onChange:applyConfig}));root.append(configuration);
   const resolved=resolvePlanTasks(draft,facts());if(resolved.changes.length)root.append(el('p','notice',`${resolved.changes.length} tasks changed since this plan was saved.`),button('Update plan task data',()=>{const tasks={...draft.tasks};for(const item of data.items)if(tasks[item.key])tasks[item.key]=snapshotTask(item,{...data.state,completed:data.completed});change({type:'updateTasks',tasks});}));
   const validation=validatePlan(draft,facts());const status=el('div','plan-status');status.append(el('strong',validation.complete?'success':'',validation.complete?'All tasks arranged · deadline checks passed':validation.valid?'Draft · some work is not arranged':'Draft · constraints need attention'));
   const remaining=Object.values(validation.unassigned).reduce((n,v)=>n+v,0);if(remaining)status.append(el('span','hint',`${formatMinutes(remaining)} unassigned`));if(validation.issues.length){const details=el('details');details.append(el('summary','',`${validation.issues.length} checks to review`));for(const issue of validation.issues)details.append(el('p','hint',`${draft.tasks[issue.itemKey]?.title||issue.day||''} ${issue.message}`));status.append(details);}root.append(status);
   const chartTools=el('div','view-tools');chartTools.append(select('Plan chart metric',[['minutes','Estimated hours'],['tasks','Tasks']],chartMetric,v=>{chartMetric=v;draw();}));root.append(chartTools,renderLineChart({document,series:[{id:draft.id,name:'Planned remaining work',color:'#258c83',points:planSeries(draft,{...facts(),mode:'remaining'})}],metric:chartMetric,onSelectDay:day=>{openedDays.add(day);draw();root.querySelector(`[data-plan-day="${day}"]`)?.scrollIntoView?.({block:'nearest'});}}));
   if(editing)root.append(renderPlanEditor({document,plan:draft,...editing,facts:facts(),onApply:change,onClose:()=>{editing=null;draw();}}));
   const columns=el('div','plan-columns');columns.append(pool(),daily());root.append(columns);
  }else root.append(el('div','empty-state','Create a plan to organize your remaining tasks by day.'));
  if(notice)root.append(el('p',conflict?'notice':'hint',notice));if(conflict)root.append(button('Reload saved plan',async()=>{if(options.onReloadPlans){const fresh=await options.onReloadPlans();archives={...fresh.plans};data.state=fresh;}discard();conflict=false;draw();}),button('Save plan as copy',async()=>{draft=copyPlan(draft,{id:newId('plan'),name:`${draft.name.slice(0,110)} copy`,now:now()});mark(true);await save();}));
  if(Object.keys(archives).length>=2){const comparison=el('details','comparison-picker');comparison.append(el('summary','','Compare saved plans (2–4)'));for(const saved of Object.values(archives)){const box=input(`Compare ${saved.name}`,'','checkbox');box.checked=compared.has(saved.id);box.addEventListener('change',()=>{if(box.checked&&compared.size<4)compared.add(saved.id);else compared.delete(saved.id);draw();});comparison.append(field(saved.name,box));}if(compared.size>=2)comparison.append(renderPlanComparison({document,plans:[...compared].map(id=>archives[id]).filter(Boolean),facts:facts()}));root.append(comparison);}
  if(prompt){const dialog=el('section','draft-dialog');dialog.setAttribute('role','alertdialog');dialog.setAttribute('aria-label',prompt.kind==='leave'?'Unsaved plan':'Delete plan');
   if(prompt.kind==='leave'){dialog.append(el('h3','','Save your plan before leaving?'),button('Save draft and continue',async()=>{if(await save())finishPrompt(true);}),button('Discard draft changes',()=>{discard();finishPrompt(true);},'text-button'),button('Return to editing',()=>finishPrompt(false),'text-button'));}
   else{dialog.append(el('h3','',`Delete “${draft?.name}”?`),el('p','hint','This removes only this saved plan.'),button('Confirm delete plan',async()=>{if(archives[draft.id]){const result=await planClient.remove(draft.id,draft.revision);if(!result.ok){notice=result.message;prompt=null;draw();return;}delete archives[draft.id];delete data.state.plans[draft.id];compared.delete(draft.id);}draft=Object.values(archives)[0]?structuredClone(Object.values(archives)[0]):null;mark(false);prompt=null;draw();}),button('Cancel delete plan',()=>{prompt=null;draw();},'text-button'));}root.append(dialog);
  }
  if(focusId){const target=[...root.querySelectorAll('[data-control-id]')].find(n=>n.dataset.controlId===focusId);target?.focus();if(cursor!=null&&target?.type==='text')target.setSelectionRange(cursor,cursor);}
 }
 function pool(){const panel=el('aside','task-pool');panel.append(el('h3','','Remaining tasks'));const search=input('Search tasks',filters.query);search.addEventListener('input',()=>{filters.query=search.value;draw();});const contexts=new Map();for(const item of data.items)(item.contextCodes||[]).forEach((code,index)=>contexts.set(code,item.contexts[index]||code));
  panel.append(search,select('Task course',[['all','All courses / calendars'],...contexts],filters.course,v=>{filters.course=v;draw();}),select('Task sort',[['dueAsc','Deadline: nearest first'],['dueDesc','Deadline: latest first'],['estimateAsc','Estimate: shortest first'],['estimateDesc','Estimate: longest first']],filters.sort,v=>{filters.sort=v;draw();}),select('Task arrangement',[['all','All remaining tasks'],['none','Unscheduled'],['partial','Partially scheduled'],['full','Scheduled']],filters.status,v=>{filters.status=v;draw();}));const group=input('Group tasks by course','','checkbox');group.checked=filters.group;group.addEventListener('change',()=>{filters.group=group.checked;draw();});panel.append(field('Group by course',group));
  const amount=key=>draft.segments.filter(s=>s.itemKey===key).reduce((n,s)=>n+(Date.parse(s.endAt)-Date.parse(s.startAt))/60000,0);const estimate=item=>draft.tasks[item.key]?.estimateMinutes||resolveEstimate(item,data.state).minutes;
  const filtered=data.items.filter(i=>!i.completed&&!data.completed[i.key]&&i.title.toLocaleLowerCase().includes(filters.query.trim().toLocaleLowerCase())&&(filters.course==='all'||i.contextCodes?.includes(filters.course))).filter(i=>filters.status==='all'||(filters.status==='none'?amount(i.key)===0:filters.status==='partial'?amount(i.key)>0&&amount(i.key)<estimate(i):amount(i.key)>=estimate(i)));
  filtered.sort((a,b)=>{const n=filters.sort.startsWith('due')?Date.parse(a.dueAt||a.fixedStartAt)-Date.parse(b.dueAt||b.fixedStartAt):estimate(a)-estimate(b);return n*(filters.sort.endsWith('Desc')?-1:1)||a.title.localeCompare(b.title);});
  if(filters.group)filtered.sort((a,b)=>(a.contexts[0]||'Personal').localeCompare(b.contexts[0]||'Personal'));let heading=null;
  for(const item of filtered){if(filters.group&&heading!==(item.contexts[0]||'Personal')){heading=item.contexts[0]||'Personal';panel.append(el('h4','',heading));}const row=el('div','pool-card');row.dataset.poolTask=item.key;const last=draft.segments.filter(s=>s.itemKey===item.key).map(s=>s.endAt).sort().at(-1);const urgent=taskUrgency(item,{now:now(),lastEndAt:last,completed:false});row.classList.add(`urgency-${urgent.level}`);row.append(button(`Open ${item.title}`,()=>onOpenItem?.(item.key),'task-title',item.title),el('p','hint',item.contexts.join(' · ')),el('p','hint',`${formatMinutes(estimate(item))} · ${item.type==='event'?'Fixed activity':`${amount(item.key)}/${estimate(item)} min arranged`}`));if(urgent.label)row.append(el('span',`urgency-tag ${urgent.level}`,urgent.label));
   if(item.type==='assignment'){row.draggable=true;row.addEventListener('dragstart',e=>e.dataTransfer?.setData('application/x-canvas-planner-task',item.key));row.append(button(`Arrange ${item.title}`,()=>arrange(item.key),'text-button','Arrange'));}if(!item.canvasCompleted)row.append(button(`Complete ${item.title}`,()=>onComplete?.(item.key,true),'text-button','✓ Complete'));panel.append(row);
  }if(!filtered.length)panel.append(el('p','hint','No remaining tasks match your filters.'));const future=data.items.filter(i=>i.type==='assignment'&&!i.completed&&i.endDay>draft.range.endDate).length;if(future)panel.append(el('p','hint',`${future} future tasks fall after this plan range; use Arrange to include one.`));return panel;
 }
 function daily(){const panel=el('section','daily-plan');panel.append(el('h3','','Your days'));const points=new Map(planSeries(draft,{...facts(),mode:'remaining'}).map(p=>[p.day,p]));const resolved=resolvePlanTasks(draft,facts());
  daysBetween(draft.range.startDate,draft.range.endDate).forEach((day,index)=>{const group=el('details','plan-day');group.dataset.planDay=day;group.open=index<7||openedDays.has(day);group.addEventListener('toggle',()=>{if(group.open)openedDays.add(day);else openedDays.delete(day);});const point=points.get(day);const name=day===today()?'Today':day===addDays(today(),1)?'Tomorrow':new Intl.DateTimeFormat('en-US',{weekday:'short',month:'short',day:'numeric',timeZone:'UTC'}).format(new Date(`${day}T12:00:00Z`));group.append(el('summary','',`${name} · ${day} · ${point.tasks} tasks · ${formatMinutes(point.minutes)}`));group.addEventListener('dragover',e=>e.preventDefault());group.addEventListener('drop',e=>{e.preventDefault();const key=e.dataTransfer?.getData('application/x-canvas-planner-task');if(data.items.some(i=>i.key===key))arrange(key,day);});
   const blocks=draft.segments.filter(s=>dateKey(s.startAt,draft.timeZone)===day).sort((a,b)=>a.order-b.order||a.startAt.localeCompare(b.startAt));for(const segment of blocks){const task=resolved.tasks[segment.itemKey];if(!task)continue;const row=el('div',`planned-row${task.completed?' completed':''}`);row.append(button(`Open ${task.title}`,()=>onOpenItem?.(task.key),'task-title',task.title),el('span','hint',`${formatClock(segment.startAt)}–${formatClock(segment.endAt)} · ${formatMinutes((Date.parse(segment.endAt)-Date.parse(segment.startAt))/60000)} / ${formatMinutes(task.estimateMinutes)}`));const last=draft.segments.filter(s=>s.itemKey===task.key).map(s=>s.endAt).sort().at(-1);const urgent=taskUrgency(data.items.find(i=>i.key===task.key)||task,{now:now(),lastEndAt:last,completed:task.completed});if(urgent.label)row.append(el('span',`urgency-tag ${urgent.level}`,urgent.label));if(!task.known)row.append(el('span','notice','Not currently loaded'));
    row.append(button(`Edit block ${segment.id}`,()=>arrange(task.key,day,segment.id),'text-button','Edit'),button(`Remove block ${segment.id}`,()=>change({type:'removeSegment',id:segment.id}),'text-button','Remove'),button(`Lock block ${segment.id}`,()=>change({type:'lock',id:segment.id,locked:!segment.locked}),'text-button',segment.locked?'Unlock':'Lock'),button(`Move block ${segment.id} up`,()=>{const ids=blocks.map(s=>s.id);const i=ids.indexOf(segment.id);if(i>0){[ids[i-1],ids[i]]=[ids[i],ids[i-1]];change({type:'reorder',orderedIds:ids});}},'text-button','↑'));
    if(!task.completed&&!data.items.find(i=>i.key===task.key)?.canvasCompleted)row.append(button(`Complete ${task.title}`,()=>onComplete?.(task.key,true),'text-button','✓ Complete'));group.append(row);
   }for(const event of Object.values(draft.tasks).filter(t=>t.type==='event'&&t.startDay<=day&&t.endDay>=day))group.append(el('p',resolved.tasks[event.key]?.completed?'hint completed':'hint',`${event.title} · Fixed activity`));if(!blocks.length)group.append(el('p','hint','Drop a task here or use Arrange in the task list.'));panel.append(group);
  });return panel;
 }
 const api={render(){draw();return root;},setData(next){data={...data,...next};for(const [id,p]of Object.entries(data.state.plans))if(!archives[id]||p.revision>archives[id].revision)archives[id]=p;draw();},requestLeave,destroy(){destroyed=true;prompt?.resolve?.(false);prompt=null;root.remove();}};return api;
}
