import {setText,translate} from './i18n.js';
import {ui,newId} from './ui.js';import {validateSettings} from './planning-settings.js';import {resolveEstimate} from './estimates.js';
import {defaultHistoryFilter} from './tasks.js';
export function renderScheduleEditor({document,schedule,onChange}){
 const {el,input,field,button}=ui(document);const panel=el('section','schedule-editor');
 panel.append(el('p','hint','Daily capacity includes the actual time occupied by calendar events. Set capacity to 0 for a rest day.'));
 for(let i=0;i<7;i++){const day=schedule.weekdays[i];const name=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][i];const row=el('div','schedule-row');row.append(el('strong','',name),field('From',input(`${name} work start`,day.start,'time',v=>{day.start=v;onChange?.();})),field('Until',input(`${name} work end`,day.end,'time',v=>{day.end=v;onChange?.();})),field('Minutes',input(`${name} capacity minutes`,day.maxMinutes,'number',v=>{day.maxMinutes=v;onChange?.();})));panel.append(row);}
 const exceptions=el('div');const drawExceptions=()=>{exceptions.replaceChildren();for(const [date,day]of Object.entries(schedule.exceptions).sort()){const row=el('div','schedule-row');row.append(el('strong','',date),field('From',input(`${date} work start`,day.start,'time',v=>{day.start=v;onChange?.();})),field('Until',input(`${date} work end`,day.end,'time',v=>{day.end=v;onChange?.();})),field('Minutes',input(`${date} capacity minutes`,day.maxMinutes,'number',v=>{day.maxMinutes=v;onChange?.();})),button(`Remove override ${date}`,()=>{delete schedule.exceptions[date];drawExceptions();onChange?.();},'text-button','Remove'));exceptions.append(row);}};
 const date=input('Override date','','date');panel.append(el('h3','','Date overrides'),exceptions,date,button('Add date override',()=>{if(!date.value)return;schedule.exceptions[date.value]={start:'09:00',end:'21:00',maxMinutes:0};drawExceptions();onChange?.();}));drawExceptions();return panel;
}
export function renderPlanningSettings({document,state,contexts,onSave}){
 const {el,input,field,button,select}=ui(document);const draft=structuredClone(state.settings);const panel=el('section','planning-settings');const notice=el('p','notice');notice.setAttribute('role','status');notice.setAttribute('aria-live','polite');panel.append(el('h2','','Estimates & pressure'),el('p','hint','Manual estimates override the first matching enabled rule, then the default. Saved plans keep their own estimates.'));
 draft.historyFilter||=defaultHistoryFilter();
 const history=el('div','history-settings');history.append(el('h3','','Historical homework'),el('p','hint','Hide expired homework before the current semester: January–May, June–July, or August–December. You can view hidden tasks in the task list.'));
 const months=input('Ignore overdue older than months',draft.historyFilter.months,'number',value=>{draft.historyFilter.months=value;});months.min='1';months.max='24';months.step='1';months.disabled=draft.historyFilter.mode!=='months';
 history.append(field('History filter',select('Historical homework mode',[['semester','Current semester'],['months','Older than X months'],['off','Show all history']],draft.historyFilter.mode,value=>{draft.historyFilter.mode=value;months.disabled=value!=='months';})),field('Months',months));panel.append(history);
 const top=el('div','form-grid');for(const [label,key]of [['Default estimate minutes','defaultMinutes'],['Yellow pressure starts at','yellowFrom'],['Red pressure starts at','redFrom']])top.append(field(label,input(label,draft[key],'number',v=>{draft[key]=v;drawPreview();})));panel.append(top,el('h3','','Estimate rules'));
 const rules=el('div');const preview=el('div','estimate-preview');preview.dataset.estimatePreview='';let previewTitle='';let previewContext=contexts[0]?.code||'';
 const drawPreview=()=>{const result=resolveEstimate({key:'preview',title:previewTitle,contextCodes:[previewContext]},{settings:draft,estimates:{}});setText(preview,`${result.minutes} min · ${result.label}`);};
 const drawRules=()=>{rules.replaceChildren();draft.rules.forEach((rule,index)=>{const label=`Rule ${index+1}`;const row=el('div','rule-card');const enabled=input(`${label} enabled`,'','checkbox');enabled.checked=rule.enabled;enabled.addEventListener('change',()=>{rule.enabled=enabled.checked;drawPreview();});
  row.append(field('Enabled',enabled),field('Name',input(`${label} name`,rule.name,'text',v=>{rule.name=v;drawPreview();})),field('Match type',select(`${label} type`,[['titleContains','Title contains'],['contextIs','Course / calendar is']],rule.type,v=>{rule.type=v;rule.value=v==='contextIs'?(contexts[0]?.code||''):'';drawRules();drawPreview();})),field('Match',rule.type==='contextIs'?select(`${label} match`,contexts.map(c=>[c.code,c.name,true]),rule.value,v=>{rule.value=v;drawPreview();}):input(`${label} match`,rule.value,'text',v=>{rule.value=v;drawPreview();})),field('Minutes',input(`${label} minutes`,rule.minutes,'number',v=>{rule.minutes=v;drawPreview();})));
  row.append(button(`Move ${label} up`,()=>{if(index){[draft.rules[index-1],draft.rules[index]]=[draft.rules[index],draft.rules[index-1]];drawRules();drawPreview();}},'text-button','↑'),button(`Move ${label} down`,()=>{if(index<draft.rules.length-1){[draft.rules[index+1],draft.rules[index]]=[draft.rules[index],draft.rules[index+1]];drawRules();drawPreview();}},'text-button','↓'),button(`Delete ${label}`,()=>{draft.rules.splice(index,1);drawRules();drawPreview();},'text-button','Delete'));rules.append(row);
 });};
 panel.append(rules,button('Add estimate rule',()=>{draft.rules.push({id:newId('rule'),name:translate(document,'New rule'),enabled:true,type:'titleContains',value:'',minutes:30});drawRules();drawPreview();}),el('h3','','Try a rule'),field('Title',input('Preview title','','text',v=>{previewTitle=v;drawPreview();})),field('Course / calendar',select('Preview calendar',contexts.map(c=>[c.code,c.name,true]),previewContext,v=>{previewContext=v;drawPreview();})),preview);
 const schedules=el('details','schedule-settings');schedules.append(el('summary','','Defaults for new plans'),field('Default plan days',input('Default plan days',draft.schedule.horizonDays,'number',v=>{draft.schedule.horizonDays=v;})),renderScheduleEditor({document,schedule:draft.schedule}));panel.append(schedules,notice);
 const save=button('Save planning settings',async()=>{const result=validateSettings(draft);if(!result.value){setText(notice,result.errors);return;}save.disabled=true;try{await onSave(result.value);notice.className='success';setText(notice,'Planning settings saved.');}catch(error){notice.className='notice';setText(notice,error.message||'Could not save settings.');}finally{save.disabled=false;}});panel.append(save);drawRules();drawPreview();return panel;
}
